### ISSUE TITLE
 spend data is erroneously separated and does not have a default

### ISSUE THREAD

**Issue by izabelamartins** [mbilling/PBIConnectors#14]
the spend data on Facebook Ads Connector is wrong because for example, the real value is $ 4.50 and comes as $ 450, even if we divide it by 100, there will be other numbers where that division can not be made (number in the same case that should be split for 10, for example) and so the value stays wrong. Therefore, the other metrics (CPC, CPM) are calculated incorrectly because they all depend on the spend value for the calculation.

**Comment by mbilling** [comment]
This is a localization issue.
Solution: If you switch to en-us in the options it should work.

New feature:
When the connector was made it wasn't a possibility to do this better. 
But features that can fix this problem has since been added to the Power Query language.
I will add this soon! Stay tuned!
